"""Configuration settings for the Underwater Plant Ecosystem Simulation"""
from enum import Enum, auto

# Screen settings
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60
TITLE = "Underwater Plant Ecosystem"

# Particles
PARTICLE_COUNT = 180
SEDIMENT_COUNT = 120
PLANKTON_COUNT = 120
PARTICLE_MIN_SIZE = 1
PARTICLE_MAX_SIZE = 4
PARTICLE_MIN_SPEED = 0.1
PARTICLE_MAX_SPEED = 0.5
SEDIMENT_COLOR = (180, 160, 140)
PLANKTON_COLOR = (100, 200, 100)
PARTICLE_ALPHA = 90

# Visual effects
LIGHT_RAY_COUNT = 10
LIGHT_RAY_ALPHA = 40
LIGHT_RAY_COLOR = (200, 230, 255)
BUBBLE_CHANCE = 0.003
BUBBLE_COLOR = (200, 230, 255)

# Soil settings
SOIL_CELL_SIZE = 12
SOIL_BASE_NUTRIENT = 0.9
SOIL_SURFACE_BONUS = 0.25
SOIL_DEPLETED_COLOR = (85, 80, 75)
SOIL_FERTILE_COLOR = (110, 70, 45)
SOIL_SOLIDIFY_THRESHOLD = 0.4
SOIL_MAX_NUTRIENT = 1.5

# Terrain zones
WATER_LINE_Y = 150
BEACH_SLOPE_END = 200
STEEP_DROP_END = 400
TERRAIN_BASE_HEIGHT = 700

# Colors - Environment
SKY_COLOR = (152, 219, 249)
BEACH_COLOR = (235, 210, 170)
TERRAIN_COLOR = (60, 50, 45)
TERRAIN_DARK_COLOR = (45, 35, 30)
WATER_SURFACE_COLOR = (80, 170, 210)
WATER_DEEP_COLOR = (15, 40, 80)
HAZE_COLOR = (20, 50, 90)

# Plant types
KELP_HEIGHT_MIN = 100
KELP_HEIGHT_MAX = 200
KELP_SEGMENTS = 14
KELP_SWAY_SPEED = 1.2
KELP_SWAY_AMPLITUDE = 20
KELP_COLOR = (45, 110, 45)
KELP_HIGHLIGHT = (80, 160, 80)
KELP_WIDTH = 6
KELP_DEPTH_MAX = 0.40

SEAGRASS_HEIGHT_MIN = 40
SEAGRASS_HEIGHT_MAX = 90
SEAGRASS_SEGMENTS = 10
SEAGRASS_SWAY_SPEED = 2.2
SEAGRASS_SWAY_AMPLITUDE = 12
SEAGRASS_COLOR = (60, 170, 60)
SEAGRASS_HIGHLIGHT = (120, 220, 120)
SEAGRASS_WIDTH = 3
SEAGRASS_DEPTH_MIN = 0.20
SEAGRASS_DEPTH_MAX = 0.70

ALGAE_HEIGHT_MIN = 15
ALGAE_HEIGHT_MAX = 60
ALGAE_SEGMENTS = 5
ALGAE_SWAY_SPEED = 2.8
ALGAE_SWAY_AMPLITUDE = 6
ALGAE_COLOR = (30, 80, 30)
ALGAE_HIGHLIGHT = (60, 120, 60)
ALGAE_WIDTH = 4
ALGAE_DEPTH_MIN = 0.60

# Root system settings
ROOT_BASE_THICKNESS = 5
ROOT_BASE_GROWTH_RATE = 0.6
ROOT_MAX_NODES = 120
ROOT_MAX_DEPTH = 35
ROOT_BRANCH_CHANCE = 0.15
ROOT_UPTAKE_CAPACITY = 0.02
ROOT_TRANSPORT_LOSS = 0.005
ROOT_BASE_COLOR = (130, 100, 80)
ROOT_ACTIVE_COLOR = (210, 170, 110)
ROOT_TIP_COLOR = (255, 220, 150)
ROOT_ENERGY_HUNGRY_THRESHOLD = 5.0
ROOT_HIGH_ENERGY_SLOWDOWN = 15.0
ROOT_MAX_GROWTH_MULTIPLIER = 3.5

# Plant life cycle
SEED_GROWTH_ENERGY = 1.0
MATURE_ENERGY_THRESHOLD = 3.5
PLANT_BASE_MAINTENANCE = 0.15
PLANT_SIZE_MAINTENANCE_FACTOR = 0.35
PLANT_MAX_AGE = 60.0
SEED_PRODUCTION_ENERGY = 5.5
SEED_PRODUCTION_COST = 3.0
FLOWERING_ENERGY_THRESHOLD = 7.0
FLOWERING_DURATION = 12.0
DECOMPOSITION_NUTRIENT_RETURN = 0.8
DECOMPOSITION_DURATION = 8.0

# Evolution settings
MUTATION_RATE = 0.2
MUTATION_STRENGTH = 0.15

# Fish Physics
FISH_MAX_FORCE = 4.5
FISH_MAX_SPEED = 140.0
FISH_DRAG = 0.96
FISH_MIN_SPEED = 15.0

# Sensory System (Radar)
FISH_SENSOR_RANGE = 250.0
FISH_SENSOR_ARC = 1.2
FISH_SENSORS_COUNT = 3

# Fish lifecycle
FISH_LARVA_DURATION = 12.0
FISH_JUVENILE_DURATION = 20.0
FISH_ADULT_DURATION = 150.0
FISH_ELDER_DURATION = 80.0
FISH_MAX_AGE = FISH_LARVA_DURATION + FISH_JUVENILE_DURATION + FISH_ADULT_DURATION + FISH_ELDER_DURATION

# Species-Specific Modifiers
CLEANER_FISH_SPEED_MULT = 0.85
PREDATOR_SPEED_MULT = 0.95
PREDATOR_DASH_SPEED_MULT = 2.4
PREDATOR_DASH_DURATION = 0.8
PREDATOR_DASH_COOLDOWN = 3.5

# Reproduction & Energy
FISH_MAX_ENERGY = 50.0
FISH_HUNGER_THRESHOLD = 30.0 # Will start looking for food sooner
FISH_MATING_THRESHOLD = 35.0
FISH_REPRODUCTION_COST = 12.0
FISH_EGG_HATCH_TIME = 10.0

# Populations
FISH_MAX_POPULATION = 40
CLEANER_FISH_MAX_POPULATION = 15
PREDATOR_MAX_POPULATION = 4

class FishState(Enum):
    RESTING = auto()  # Near plants, low speed
    HUNTING = auto()  # Looking for food
    FLEEING = auto()  # Evading predator
    MATING = auto()   # Looking for partner
    NESTING = auto()  # Pregnant, looking for plant base to lay egg
